#!/bin/sh

echo "Restarting daemons (IRC)"
sudo god stop notify-me-irc
# sudo god restart notify-me-irc
# sleep 60

echo "Restarting sidekiq"
sudo god restart notify-me-sidekiq
# sleep 30

echo "Reload nginx.."
sudo service nginx reload

echo "Restarting app.."
touch ./tmp/restart.txt
