#!/bin/sh

echo "Reload nginx.."
sudo service nginx reload

echo "Restarting app.."
touch tmp/restart.txt

echo "Restarting sidekiq"
sudo god restart notify-me-sidekiq

echo "Restarting daemons (IRC)"
sudo god restart notify-me-irc
